### ISSUE TITLE
Allow multi-language users to pick which language model they wish to use instead of auto-detecting.

### ISSUE THREAD

**Issue by Continous** [futo-org/voice-input#22]
The Problem:

Currently, the language model must autodetect the language which the user is speaking. This can take a non-insignificant amount of time. For quick messages, this is inconvenient.

(My) Proposed Solution:

At some point prompt the user to choose the language, after which the prompt can time out and the language can then be automatically chosen instead. This allows users to easily use the feature however they wish, be it through manual selection, or the already present automatic detection.

Potential Downsides:

- Could introduce _additional_ delay for users who use the autodetect feature.

- - This assumes FUTO doesn't do any processing during the timeout. It could be that the "timeout" is actually just however long it takes FUTO to detect the correct language.

- In cases where a user accidentally selects the incorrect language, it may inconvenience the user instead of adding convenience.

Potential Indirect Upsides:

- In cases in which FUTO is incidentally or accidentally detecting the wrong language (IE if someone is speaking a specifically language, but with a disproportionate amount of another language's nouns) this feature could facilitate a workaround.
- This could facilitate on-the-fly selection of language models, allowing users to not have to invest in specific language models before beginning use of FUTO. A default of English's fast/simple language model would be a good OOB solution.

Additional Comments:

I do not know how FUTO implements its multi-language feature, but if performance is in any way proportional to the number of language models used, this could greatly help those who speak a plurality of languages.

**Comment by abb128** [comment]
An option for this has been added in v1.2.5 which is going to be released soon

**Comment by Continous** [comment]
> An option for this has been added in v1.2.5 which is going to be released soon

I am very happy to hear this!
