### ISSUE TITLE
Galaxy S22 Ultra (Samsung Keyboard) issue with FUTO - how do I resolve?

### ISSUE THREAD

**Issue by cleverestx** [futo-org/voice-input#25]
During install it told me the Samsung keyboard won't work, as the microphone icons are hard-coded for Samsung or Google only...how do I resolve this? Any recommended workaround/keyboards from the Google Playstore, etc?

**Comment by abb128** [comment]
Some recommendations are listed in the app in the Help menu. You can try [AnySoftKeyboard](https://play.google.com/store/apps/details?id=com.menny.android.anysoftkeyboard&hl=en_US&gl=US), [OpenBoard](https://f-droid.org/en/packages/org.dslul.openboard.inputmethod.latin/), or SwiftKey (isn't as private as the other options)
