### ISSUE TITLE
[Feature Request] Prevent the screen from turning off while the app is processing the voice input.

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [futo-org/voice-input#26]
Firstly, I'd like to thank the FUTO team for developing such a handy app! This whole issue was dictated with FUTO, with only minor corrections. Now, onto the issue:

I have my screen timeout set to 15 seconds, if I don't interact with my device within that time frame, the screen will turn off. More often than not, the FUTO app will be processing the input for longer than that time. This is a problem because if the screen turns off while it's still processing the input, then the FUTO voice-app will stop processing it, and will not resume when I turn on the screen again. This causes me to have to dictate everything I said to the app again, while I make sure to tap the screen every now and then so the screen doesn't turn off.

What I propose to fix this is for the app to use [Android wakelocks](https://developer.android.com/training/scheduling/wakelock), which would prevent the screen from turning off automatically.

**Comment by voidplayer** [comment]
Instead, why not allow processing while phone is turned off?

It takes up to a minute processing, which i dont mind, but id like to put the phone in my pocket and grab it later. I cant put the phone on my pocket unlocked

**Comment by ItsIgnacioPortal** [comment]
> Instead, why not allow processing while phone is turned off?
> 
> It takes up to a minute processing, which i dont mind, but id like to put the phone in my pocket and grab it later. I cant put the phone on my pocket unlocked

I suppose both could be done without any problems. It's just wakelocks and persistent notifications

**Comment by abb128** [comment]
Apologies for not closing earlier, a wake lock was added in v1.2.6
