### ISSUE TITLE
Add English-244 (Whisper `small.en`)

### ISSUE THREAD

**Issue by milkey-mouse** [futo-org/voice-input#27]
I have a beefy phone and, unfortunately, a voice made for print. In my experience, the English-only Whisper base model, aka `base.en`, aka English-74, is alright, but I do get better results from Whisper `small.en` (what this app would probably call English-244). It looks like the app can already run these larger models, as there's a Multilingual-244 model (on by default when I enable non-English languages and slow models, in fact). It'd be nice to provide this option for even slower decoding in exchange for better punctuation and lower word error rate.

**Comment by abb128** [comment]
This will be added in the next update along with some speed optimizations

**Comment by Kallinteris-Andreas** [comment]
@abb128  reminder to close

**Comment by Kallinteris-Andreas** [comment]
Also it is matter of time before someone asks for medium and large so it might be a good idea to add them
