### ISSUE TITLE
Version # on website?

### ISSUE THREAD

**Issue by DiagonalArg** [futo-org/voice-input#29]
I wonder if you'd be willing to make the version number available someplace on this page: https://voiceinput.futo.org/ 

This will help us identify when a new version is available.  It will in particular help those of us who use [Obtainium](https://github.com/ImranR98/Obtainium).  For that, the version# could be anywhere in the html, including as a part of the link to the .apk, eg as:
https://voiceinput.futo.org/VoiceInput/standalone.xx.yy.zz.apk

Thanks for considering it!

**Comment by abb128** [comment]
I've added this. You can also use this to get the version in a simple formatted way, used by the auto update checker - http://voiceinput.futo.org/VoiceInput/voice_input_version_standalone

**Comment by DiagonalArg** [comment]
Thank you.
