### ISSUE TITLE
Inserting space before the input

### ISSUE THREAD

**Issue by Nomkid** [futo-org/voice-input#3]
" This is me testing with the voice input right now."

Everything between the quotes was written by Voice Input. When it begins generating, there's no space before the input. But once it exits, it inserts a space at the beginning.

Downloaded from the F-Droid repo listed on the website.
Running LineageOS 19.1 (Android 12)

**Comment by rakijagamer-2003** [comment]
I noticed the same issue while testing the voice input too.

**Comment by TheWebMachine** [comment]
Same for me on Samsung Galaxy Fold 5 downloaded from Play Store.

**Comment by abb128** [comment]
This should be fixed in the next update (v1.2.3+). If you continue to have issues with the space and you're running v1.2.3+, feel free to open another issue
