### ISSUE TITLE
Payment not working

### ISSUE THREAD

**Issue by DiagonalArg** [futo-org/voice-input#30]
I've installed the standalone .apk on a Pixel 7 running GrapheneOS.  When I try to pay:

1. It doesn't tell me how much.  Or, is this just based on our donating what we like?  Please clarify.
2. It asks for my postal code, then responds, "Value is invalid for CA."  But it's not!

**Comment by abb128** [comment]
Can you give an example of a post code that doesn't work? You should be able to just enter it, some examples of how you can format it are `k1a0b1` or `K1A 0B1`. There does appear to be a problem if you put a trailing space though, so make sure there's no trailing space

**Comment by DiagonalArg** [comment]
Hm, if CA means Canada, then it's responding to my VPN.  I'm in US.

**Comment by abb128** [comment]
It does indeed mean Canada, and it's expecting a Canadian post code. You can manually change your country but currently you have to get past the post code screen first. You can try entering a canadian post code like `k1a0b1`, then change the country to US, enter your US zip code, and make sure currency is set to USD. You can also try switching your VPN to a US IP address.

**Comment by DiagonalArg** [comment]
> It does indeed mean Canada, and it's expecting a Canadian post code. You can manually change your country but currently you have to get past the post code screen first. You can try entering a canadian post code like `k1a0b1`, then change the country to US, enter your US zip code, and make sure currency is set to USD. 

Ok.  I'll take that as a work-around!  :)

**Comment by tom-futo** [comment]
This should be fixed in FUTO Pay
