### ISSUE TITLE
Publish releases with APK on GitHub/GitLab or otherwise support Obtainium

### ISSUE THREAD

**Issue by anton-isidore** [futo-org/voice-input#31]
Hi, I use Obtainium a lot and the FUTO Voice input cannot be added as it does not publish raw APKs in a structured way.

What is Obtainium? -> https://github.com/ImranR98/Obtainium

Most convenient is to just release APKs on GitHub/GitLab as it's easy to track versions. It is also possible to just tweak your HTML raw APKs download page so new versions can be recognized.

**Comment by abb128** [comment]
You can install the app through Obtainium by entering the source URL as https://app.futo.org/fdroid/repo/ , selecting the source as F-Droid Third-Party Repo, and setting the App ID to `org.futo.voiceinput`

**Comment by anton-isidore** [comment]
Great, thanks. This works well. : ❤️

**Comment by Lanchon** [comment]
(please close this issue)
