### ISSUE TITLE
FUTO repo lagging behind Play Store

### ISSUE THREAD

**Issue by PacoBell** [futo-org/voice-input#34]
Currently, the FUTO F-Droid repo is advertising v1.2.5 as the latest version while the Play Store has v1.2.6 available. Did someone forget to update the repo?

**Comment by abb128** [comment]
New releases are rolled out partially to minimize the impact in case there's significant regressions/bugs, and at this time only Play Store supports staged rollout. Currently v1.2.6 is at 33% rollout on Play Store. F-Droid and Standalone will be updated along with a 100% Play Store rollout soon
