### ISSUE TITLE
Add/Train in custom words which are not in the dictionary.

### ISSUE THREAD

**Issue by laundmo** [futo-org/voice-input#38]
i've been using it a bit now, but it seems to lack some words which commonly come up since i'm a programmer, like YAML, TOML, and other specific words.

some ability to add in custom words, maybe by training them in, would be great, though i understand it might be difficult if the models dont support it in some way.

**Comment by abb128** [comment]
This has been implemented in v1.3.2, you can now set a personal dictionary which gets prompted to the model

**Comment by slmb3** [comment]
Is the personal dictionary meant to be comma delimited? Newline delimited?
