### ISSUE TITLE
Disperring text after dictation

### ISSUE THREAD

**Issue by EroJasper** [futo-org/voice-input#4]
I told my friend about this app and we both came to the same conclusion. We are both on Samsung phones and I'm not sure if that has something to do with it. After dictating something, the text shows up for a split second, and then disappears. It seems that it only started after I just barely updated the app. I definitely want to donate and support what you were doing. I hope this helps you track down and squash the bug.

**Comment by abb128** [comment]
Sorry to hear you're having issues. Could you confirm which keyboard you're using and which app are you typing into (or whether it affects every app)?

Could you also try uninstalling the app and installing the previous version to check if it works? https://voiceinput.futo.org/VoiceInput/standalone-old-13.apk

**Comment by castatech** [comment]
Having same issue. For me initially all worked great and it randomly  started later. Using open board

**Comment by abb128** [comment]
@EroJasper @castatech I pushed v1.2.4 standalone update which should fix this, can you try it and let me know if it works now?

https://voiceinput.futo.org/VoiceInput/standalone.apk

**Comment by Benchamoneh** [comment]
@abb128 first tests look good! Given that the current version in the Play Store also worked initially I'll come back to you again in a day or 2 to confirm if it stays working, but it's already an improvement!

**Comment by castatech** [comment]
Agreed. Seems to be working for me too. This is an amazing product and I can't wait to tell everyone about it!

**Comment by TheWebMachine** [comment]
This standalone version seems to have fixed the issue for me, too. Kudos!

**Comment by EroJasper** [comment]
> @EroJasper @castatech I pushed v1.2.4 standalone update which should fix this, can you try it and let me know if it works now?
> 
> https://voiceinput.futo.org/VoiceInput/standalone.apk

I apologize for my absenc. I've been busy this Saturday. It seems to be working now thanks to that. Thank you for your quick bug squashing. I really appreciate it. I definitely want to see more of my friends use this with its amazing privacy standards. Amazing work, abb123!

**Comment by abb128** [comment]
Thank you for reporting this!
