### ISSUE TITLE
F-Droid repo expired certificate

### ISSUE THREAD

**Issue by ryanfreeth** [futo-org/voice-input#41]
It looks like the certificate for app.futo.org expired today and I cannot install any apps via F-Droid

**Comment by abb128** [comment]
Everything appears to be working currently, if this is still an issue can you share a screenshot of the error message you're getting?

**Comment by ryanfreeth** [comment]
Aha! The certificate was refreshed. I must have had bad luck with the short window it was expired for. 
![image](https://github.com/futo-org/voice-input/assets/1455939/ffe2b8d3-0c08-4f49-8107-db68cd11cd2f)
