### ISSUE TITLE
Access output text from 3rd party apps

### ISSUE THREAD

**Issue by hugbear** [futo-org/voice-input#42]
I've been able to successfully invoke FUTO V.I. from MacroDroid (automation app) by sending the intent provided in the [Readme](https://gitlab.futo.org/alex/voiceinput#api-support) (android.speech.action.RECOGNIZE_SPEECH implicit intent). The voice recognition floating window starts in listening mode, processes the speech, accurately recognizes the speech and then it immediately closes.

Is there a way the recognized text could be provided to / accessed by the invoking app to be further processed?

For what it's worth, [this is the Macrodroid macro](https://ibb.co/PM71krT) and [these are the 'Send Intent' parameters](https://ibb.co/ZWZH6x8) I used (basically, nothing but the "Action" field has been set).

**Comment by abb128** [comment]
Referring to the [Android documentation](https://developer.android.com/reference/android/speech/RecognizerIntent#ACTION_RECOGNIZE_SPEECH), you're supposed to start the activity using startActivityForResult, and in results if you get the [EXTRA_RESULTS](https://developer.android.com/reference/android/speech/RecognizerIntent#EXTRA_RESULTS) as ArrayList<String>, the first element will contain the output text. Some other voice recognizers may return multiple results in the array list sorted by confidence, but FUTO Voice Input only returns one.

**Comment by hugbear** [comment]
Thank you. This _does_ answer my question (although it seems MacroDroid can't do startActivityForResult - at least for now).
