### ISSUE TITLE
Hacker's Keyboard support

### ISSUE THREAD

**Issue by DarrenWarrenV** [futo-org/voice-input#46]
Hi, are there any plans for Hacker's Keyboard support?

https://github.com/klausw/hackerskeyboard

I'm using it for years and it has everything that's needed (terminal, exagear, winlator etc.)

**Comment by abb128** [comment]
Support is something that has to be implemented on the keyboard side. It looks like Hacker's Keyboard has a voice button but from my rudimentary testing I couldn't get it to work on modern android, and the project doesn't seem to get updated anymore. As an alternative you could try Unexpected Keyboard https://github.com/Julow/Unexpected-Keyboard

**Comment by DarrenWarrenV** [comment]
Yes, this is exactly the one that I've been switching between. I'll try to write on the project's Github page! Thank you
