### ISSUE TITLE
"Automatically stop on silence" Setting Ease of use

### ISSUE THREAD

**Issue by WesleyFister** [futo-org/voice-input#50]
Being able to disable "Automatically stop on silence" is a great feature when it comes to long free form spoken paragraphs where you might stop and think about what to say next. However it is a bit cumbersome disable this setting every time when you want to talk for long periods.

I propose that while holding the microphone button icon (the one that is used to end the recording) the recording will not stop until the user stops holding the button.

**Comment by David-Prock** [comment]
Or a swipe for more time.
Also its own editor window so you can make manual corrections in a larger editing space, most apps just give you the space of three or four lines that you be scrolling 'sometimes' large blocks of text inside of. Now that gets Annoying.

**Comment by WesleyFister** [comment]
Yes, there are many ways to implement it. You could also have a button that will record indefinitely until you tap it again. However, I prefer the while held option as it feels in most minimalist for the user but that is just my opinion.

As I was writing this I just realized that Futo Voice Input has a maximum of 30 seconds. I assume that there might be some sort of limitation on whisper? Anyways this should be removed or at the very least lengthened significantly.

**Comment by MikeStirner** [comment]
This seems to be fixed on version 1.3.2 because you can press and hold to have it continue listening and then when you release it, it starts encoding.

**Comment by WesleyFister** [comment]
> This seems to be fixed on version 1.3.2 because you can press and hold to have it continue listening and then when you release it, it starts encoding.

My original request has been fulfilled but there is still a 30 second limit on recordings. I suppose I could close it and create a new separate issue.
