### ISSUE TITLE
Crash or failure when I tap to stop at about 28 seconds

### ISSUE THREAD

**Issue by MikeStirner** [futo-org/voice-input#54]
When I'm using the keyboard, and I don't have it set to automatically stop when there's a pause in my speech, and so I have to tap to stop it. If I tap about three seconds after it says ending soon, Then it fails to transcribe anything, although it does seem to be trying to do something, and then it resets without typing anything that I said. But if I let it go all the way to the 30 sec mark, then it works fine.

This is a problem because sometimes I don't know if I'm in that last five second period where it says ending soon. And if I tap it to stop right after it gives me that message, then I lose everything I said on accident.

**Comment by MikeStirner** [comment]
My current workaround is to see if it says ending soon before I tap to stop. If it already says ending soon, then I'll just let it end on its own. And that seems to work. Even if it says ending soon right as I'm tapping, it'll still work out okay. But if I wait three seconds after or so, that's when it has the issue.

**Comment by abb128** [comment]
Thank you for reporting this! A related issue was being looked into, this is a consistent way to reproduce it

**Comment by abb128** [comment]
A fix has been implemented and will be released in v1.3.3

**Comment by abb128** [comment]
v1.3.3 has been fully rolled out now, the bug should no longer happen

**Comment by MikeStirner** [comment]
I'm impressed at how quickly you fixed it! Thank you so much!
