### ISSUE TITLE
Adding support so Futo voice can be added as default voice input app

### ISSUE THREAD

**Issue by BurhanBudak** [futo-org/voice-input#63]
On LOS21 language options page there is a settings option to add the default input app. With Google TTS/STT app its possible to add it but not Futo. Adding this option would make Futo more universal in the OS.

![Screenshot_20240517-130314_Settings.png](https://github.com/futo-org/voice-input/assets/43676158/9d1e2657-c6e3-4e75-9a29-2370cc8a6262)

**Comment by abb128** [comment]
Duplicate of #32 (in short, that setting doesn't seem to really do much)

**Comment by BurhanBudak** [comment]
> Duplicate of #32 (in short, that setting doesn't seem to really do much)

I saw so I closed the issue. But I added a screenshot of the option.
