### ISSUE TITLE
Voice Input crashes app from keyboard or app settings

### ISSUE THREAD

**Issue by ScabbyDogmess** [futo-org/voice-input#64]
App crash since Android system update.  Using Android 14 Calyx Os on a Pixel 3xl

Worked flawlessly prior to  OS update.  Crashes within keyboard launch and voice input within app settings.

Uninstall/reinstall/clear cache, etc.

**Comment by KB8DOA** [comment]
Same here with CalyxOS 5.7 / Android 14 on Pixel 3a
What can I provide/submit from my phone to contribute towards resolving this?

**Comment by abb128** [comment]
Are you using the standalone/fdroid version or play store? Did you submit the crash report if it showed the popup?

**Comment by KB8DOA** [comment]
I installed it using Aurora Store. No crash reports/prompts are appearing.

**Comment by abb128** [comment]
Aurora Store just downloads it from Play Store, and the Play Store version disables the crash reporter in favor of Google Play's automatic crash reporter, which your phone may not have if you don't use the Play Store. I suggest uninstalling it and then installing the standalone or F-Droid version instead to see if you can send a crash report

**Comment by KB8DOA** [comment]
Futo Keyboard and Futo Voice do not appear on my F-Driod Store, so I had to use the Aurora Store.

**Comment by KB8DOA** [comment]
On Futo Circles appears...

**Comment by KB8DOA** [comment]
What repository do I need to add to F-Droid to be able to access them?

**Comment by abb128** [comment]
https://voiceinput.futo.org/ has links for either the standalone or the F-Droid repo

**Comment by KB8DOA** [comment]
![Screenshot_20240520-140842](https://github.com/futo-org/voice-input/assets/51223218/61f71a06-3d18-4198-8425-22a14f111020)

**Comment by ScabbyDogmess** [comment]
For me the crash read wait or close app.  Using f-Droid version.  Same problem happens with MS SwiftKey or Futo Keyboard or just testing input within voice input app.  Like the overlay that appear when using voice input fails to appear over the top of app
________________________________

**Comment by abb128** [comment]
Would you be able to send a bugreport taken via `adb bugreport` or developer options? https://developer.android.com/studio/debug/bug-report

**Comment by KB8DOA** [comment]
Attached:
![screenshot-2024-05-20-17-41-23-default](https://github.com/futo-org/voice-input/assets/51223218/963604c7-9df8-472c-9db0-5b4c15b1e024)
[bugreport-sargo-AP1A.240505.005-2024-05-20-17-41-23.zip](https://github.com/futo-org/voice-input/files/15381961/bugreport-sargo-AP1A.240505.005-2024-05-20-17-41-23.zip)

**Comment by abb128** [comment]
Apologies for the delay at looking into this. Can you confirm whether or not it worked before updating to CalyxOS 5.7? Looking at the logs and relevant Android code it would appear starting the audio recorder is failing as the hardware doesn't support audio recording in floating-point format, yet I can't find a reason for this to have worked up until specifically CalyxOS 5.7...

Regardless I will make a fix to use a more well-supported recording format which should fix this issue

**Comment by ScabbyDogmess** [comment]
It worked perfectly up to the 5.7 update.  It never crashed a single time prior to the update
________________________________

**Comment by ScabbyDogmess** [comment]
Tested this with same version of Calyx on a Pixel 4 and it worked with no issue.  Two reported issues on Pixel 3 variants

**Comment by abb128** [comment]
Can you check if the built-in voice input feature works in v0.1.20 of [FUTO Keyboard](https://keyboard.futo.org/) on the Pixel 3?

**Comment by ScabbyDogmess** [comment]
When using the voice input on the Pixel 3xl on the Futo Keyboard, the keyboard app closes immediately.  It crashes when testing input in the keyboard settings.
________________________________

**Comment by KB8DOA** [comment]
I have uninstalled the older Playstore verison 
and reinstalled Futo Keyboard ver 0.1.20 from F-Droid

Futo Voice Input v1.3.3 is now working on my
Pixel-3a running CalyxOS v5.7.3

Thank You

**Comment by qtf0oaia** [comment]
Same issue on Lineage 21, that Futo Voice crashes whenever I open it. It happened after the April 14 update, which was a couple megabytes bigger than the previous one.

It happens even when testing voice input within the app.

> I have uninstalled the older Playstore version and reinstalled Futo Keyboard ver 0.1.20 from F-Droid
> 
> Futo Voice Input v1.3.3 is now working on my Pixel-3a running CalyxOS v5.7.3
> 
> Finally - I can safely have STT on my phone :)
> 
> Thank You

The above from KB8DOA does not work for me. Installing Futo Keyboard allows voice to work from within that keyboard, but not using a different keyboard that uses Futo Voice.

**Comment by abb128** [comment]
FUTO Voice Input v1.3.4 includes a fix for this issue
