### ISSUE TITLE
Ability to add custom words

### ISSUE THREAD

**Issue by 766F6964** [futo-org/voice-input#65]
Is it possible to add support for users to register custom words that are usually not recognized correctly, when spoken? For example weird acronyms, brand names or specific technical terms.

**Comment by abb128** [comment]
Yes, go to Model and type in the custom dictionary field

**Comment by 766F6964** [comment]
> Yes, go to Model and type in the custom dictionary field

Awesome, I must have overlooked it at first, thanks for telling me.
